export interface HpSpell {
    id: number,
    name: string,
    energyUsage: number,
    descriptionOption: string,
    maxDamage: number,
    healing: number,
    stunned: boolean,
    confunded: boolean,
    imperio: boolean,
    crucio: boolean,
    protego: boolean,
    fiendfyre: boolean,
    antiFiendfyre: boolean,
    requiredExperience: number,
    water: boolean,
    forest: boolean,
    castle: boolean,
}
